version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./ssl/blcp.crt:/etc/nginx/ssl/nginx.cert
            - ./ssl/blcp.key:/etc/nginx/ssl/nginx.key
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
